### ISSUE TITLE
Substituir o supertest

### ISSUE THREAD

**Issue by roberto** [VamosJuntas/vamosjuntas-api#1]
O supertest parece estar sem devs para acompanhar as issues e PRs: https://github.com/visionmedia/supertest/issues/322

Vamos dar uma olhada em alternativas:
http://dareid.github.io/chakram/
https://github.com/bbc/consumer-contracts/

**Comment by wcalderipe** [comment]
Boa Roberto, eu estava tão acostumado a usar o supertest que não via o repositório fazia algum tempo. Apesar de achar que um projeto com 3,7k de stars não vá ficar a deriva por muito tempo. O que achas da gente discutir isso na sessão de terça-feira?

Em relação as sugestões não acho que devemos usar o consumer-contracts para testes de integração e gostei da interface do chakram com suporte a promises.

**Comment by MayraPaola** [comment]
@roberto @wcalderipe  está atividade é para o MVP 1?

**Comment by pedrro** [comment]
Se precisar, posso migrar para frisby.js, o que acham?

**Comment by wcalderipe** [comment]
Não acho uma boa ideia. Eu tenho a impressão de que o frisby é um projeto em marcha lenta, raramente tem alguém commitando no repositório (hoje o último commit foi a 2 meses atrás) e também há muito mais conteúdo na internet, apesar de de pouco, sobre supertest do que frisby na internet e como disse no comentário acima: não acho que um projeto com 3,7k de stars vá ficar parado por muito tempo.

Acho que essa issue pode ser fechada. O que pensam?

**Comment by wcalderipe** [comment]
Há movimentação no repositório do supertest: https://github.com/visionmedia/supertest/commits/master

**Comment by davidcostadev** [comment]
Ainda esperando uma alternativa.
