### ISSUE TITLE
Listar riscos no raio de 1km

### ISSUE THREAD

**Issue by josigama** [VamosJuntas/vamosjuntas-api#10]
Narrativa
COMO uma usuária do Vamos Juntas app
GOSTARIA de visualizar uma lista dos riscos dentro do raio de 1km
PARA encontrar locais de risco próximos a mim

Escopo:
1. Buscar no BD os riscos cadastrados
2. Filtrar os riscos cadastradas no raio de 1km

Dependências
#30 (Buscar perigos num raio x)

Critérios de aceitação
1.
DADO que estou na home do app
QUANDO verificar a localização da usuária
DEVO ver como resultado a lista dos riscos reportados naquele raio (ver história #30 - Busca de perigo num raio X e #28 - Home geolocalização)

**Comment by MayraPaola** [comment]
@josigama está pareando com alguém nesta história? Se não tiver fale com a @littlejuh que ela pode parear fora do horário da sessão do Level up.

**Comment by josigama** [comment]
@MayraPaola  Eu estou pareando com @viniciusgama  nesta história. :)

**Comment by MayraPaola** [comment]
Show!🤗

Em 18 de ago de 2016 7:49 PM, "Josi Gama" notifications@github.com
escreveu:

**Comment by josigama** [comment]
Evidencias de validação da história: 
cadastrar um novo endereço no postman: 
![image](https://cloud.githubusercontent.com/assets/13666514/18111909/b1fe3876-6ef9-11e6-96cc-d21606e924cc.png)

Endereços cadastrado no banco de dados: 
![image](https://cloud.githubusercontent.com/assets/13666514/18112133/c4732b90-6efb-11e6-982f-b1b4d6968846.png)

Procurar um ponto próximo do TECNOPUC - Colégio Marista 
![image](https://cloud.githubusercontent.com/assets/13666514/18112196/225a8528-6efc-11e6-9258-fb907570dd82.png)
Os pontos mais próximos cadastrados foram encontrados 
![image](https://cloud.githubusercontent.com/assets/13666514/18112165/00401782-6efc-11e6-8854-8ae4ef86b3e6.png)

Procurar um ponto que tenha a distancia maior do que 1000m 
![image](https://cloud.githubusercontent.com/assets/13666514/18112256/9193fc76-6efc-11e6-80d4-14d85a47ebee.png)

O request deve retornar o valor vazio
![image](https://cloud.githubusercontent.com/assets/13666514/18112287/bd499ad8-6efc-11e6-8002-1111541ad13f.png)

**Comment by gabrielacorrea** [comment]
@tayanefernandes e @josigama validaram a estória localmente e está funcionando corretamente.
Pendente: existem conflitos no PR.
@roberto : podemos resolver estes conflitos?

**Comment by josigama** [comment]
História validada conforme evidencias em anexo. Aguardando apenas a resolução de conflitos no master para mover a história para Pronto
