### ISSUE TITLE
(Front-End) Salvar no BD o nome do local

### ISSUE THREAD

**Issue by gabrielacorrea** [VamosJuntas/vamosjuntas-api#14]
Narrativa

Escopo: 
1. 
2. Filtrar os riscos cadastradas no raio de 1km
3. Ordenar a lista por por número decrescente de denúncias.

Dependências
1. Receber do front-end a informação de nome do local (#108)

Critérios de aceitação
1.
DADO que estou adicionando um novo reporte
QUANDO salvar o novo risco
DEVO salvar a informação de nome do local (exemplo: Avenida Ipiranga, 123)

2.
DADO que estou adicionando um novo reporte
QUANDO não informo o número do endereço (exemplo: Avenida Ipiranga)
DEVO ter meu reporte salvo com uma localização aproximada baseada nos pontos do Google Maps

**Comment by wcalderipe** [comment]
Estória duplicada: https://github.com/VamosJuntas/vamosjuntas/issues/114

**Comment by josigama** [comment]
@wcalderipe toda a vez que abrimos um novo pull Request ele duplica no board do waffle.

**Comment by wcalderipe** [comment]
@josigama achei que tinha sido uma confusão entre os projetos.  Agora tendo isso em vista acredito que esteja criando confusão. 

Andei dando uma olhada na nova feature do Github para projetos e é possível criar boards customizados dentro do próprio repositório e também converter cards em issues (exatamente como o Waffle). Poderíamos separar as estórias de cada projeto (o que evitaria confusões) e já centralizar todo o projeto em uma só plataforma.

Podemos discutir possíveis soluções na nossa próxima sessão? :)

**Comment by josigama** [comment]
Sim, podemos discutir sobre isso na próxima sessão :)

**Comment by josigama** [comment]
Essa história é para implementar o front-end , pois incluímos o nome do local na história #114.

**Comment by gabrielacorrea** [comment]
Esta é uma estória de front-end.
A parte do back-end já foi desenvolvida e está pronta.
