### ISSUE TITLE
Salvar reporte de risco no BD

### ISSUE THREAD

**Issue by josigama** [VamosJuntas/vamosjuntas-api#2]
Narrativa
COMO uma usuária do Vamos Juntas app
GOSTARIA de reportar um risco em um endereço
PARA que outras usuárias indo para aquele endereço saibam do risco

Escopo
1. Salvar reporte no banco de dados

Dependências
1. Ter banco de dados

Critérios de aceitação
1.
DADO que eu tento reportar um risco
QUANDO eu faço uma chamada 
DEVO visualizar este risco no  BD

**Comment by josigama** [comment]
Card pronto para validação. 

Banco de dados sem nenhum risco salvo: 
![image](https://cloud.githubusercontent.com/assets/13666514/17463994/79c5a842-5caa-11e6-8294-43c7d4ecf452.png)

Postman com request:
![image](https://cloud.githubusercontent.com/assets/13666514/17464018/b98ea0b4-5caa-11e6-9384-ee229d4ff1b4.png)
Request realizado no postman com o código 201(created)
![image](https://cloud.githubusercontent.com/assets/13666514/17464026/e4482dfc-5caa-11e6-8142-138b9816a8b6.png)

Report salvo no banco de dado: 
![image](https://cloud.githubusercontent.com/assets/13666514/17464032/100c6638-5cab-11e6-906b-32c79a6583ca.png)

**Comment by MayraPaola** [comment]
@josigama Foi feito desk check desta história?

**Comment by Rliedke** [comment]
Foi feito o review da historia e criado um debito tecnico #107, falta terminar a validação.

**Comment by tayanefernandes** [comment]
Validei essa história local, usando o passo a passo descrito pela Josi.

**Comment by josigama** [comment]
Isso Ta Ok ( ITO) by tiaquel @tayanefernandes ?

**Comment by gabrielacorrea** [comment]
QA: @tayanefernandes
